IMPORT NUMPY

In [1]:
import numpy as np

1:Create a 1D NumPy array containing the numbers from 10 to 50 (inclusive) with a step of 5.

In [6]:
array1 = np.arange(10,51,5)
array1

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

------------------------------------------------

2: Create a 4×6 array filled with zeros, then fill its third row (index 2) with the value 99.

In [5]:
array2 = np.zeros((4,6))
array2[2, :]=99 
array2

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [99., 99., 99., 99., 99., 99.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

----------------------------------------------------------

3:Given the array: arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67]). Print all elements that are greater than 50.

In [7]:
arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
print(arr[arr > 50])

[88 56 91 67]


------------------------------------------------------

4: Create a 5×5 identity matrix, then change its main diagonal (from top-left to bottom-right) to the values [10, 20, 30, 40, 50].

In [10]:
array3 = np.eye(5)
np.fill_diagonal(array3, [10, 20, 30, 40, 50])
array3

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.,  0.],
       [ 0.,  0., 30.,  0.,  0.],
       [ 0.,  0.,  0., 40.,  0.],
       [ 0.,  0.,  0.,  0., 50.]])

-----------------------------------------------------------

5: Let x = np.arange(1, 21).reshape(4, 5). Extract the following using slicing:

a. The last two rows.

b. The third column.

c. The 3×3 submatrix in the top-right corner.

In [12]:
x = np.arange(1, 21).reshape(4, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
#a
last_two_rows = x[-2:, :]
last_two_rows

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
#b
third_column = x[:, 2]
third_column

array([ 3,  8, 13, 18])

In [16]:
#c
submatrix = x[:3, 2:]
submatrix

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

------------------------------------------------------

6: Given two arrays: a = np.array([1, 2, 3, 4]) and b = np.array([[10], [20], [30]]). Compute a + b and explain the shape of the result.

In [18]:
a = np.array([1, 2, 3, 4])          # Shape (4,)
b = np.array([[10], [20], [30]])    # Shape (3, 1)
result = a + b 
result

# the result will have a shape of (3, 4) 
# to stretch the arrays so their dimensions match for the operation

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

---------------------------------------------------------

7: Normalize the following array to the range [0, 1]:
data = np.array([150, 220, 90, 300, 180, 45]).

In [23]:
data = np.array([150, 220, 90, 300, 180, 45])
norm_data = (data - data.min()) / (data.max() - data.min())
norm_data

array([0.41176471, 0.68627451, 0.17647059, 1.        , 0.52941176,
       0.        ])

----------------------------------------------

8: Standardize (z-score) the same array from question 7.

In [24]:
stand_data = (data - data.mean()) / data.std()
stand_data

array([-0.16988961,  0.66956492, -0.88942206,  1.62894153,  0.18987662,
       -1.42907141])

-----------------------------------------

9: Given the 2D array mat:

a. Compute the mean of each row.

b. Compute the sum of each column.

c. Find the maximum value in the entire matrix and its position (row, column).

In [25]:
mat = np.array([
    [4,  8,  1, 12],
    [7,  3,  9,  5],
    [11, 2,  6, 10],
    [15, 0, 14, 13]
])
mat

array([[ 4,  8,  1, 12],
       [ 7,  3,  9,  5],
       [11,  2,  6, 10],
       [15,  0, 14, 13]])

In [29]:
#a
row_means = mat.mean(axis=1)
row_means

array([ 6.25,  6.  ,  7.25, 10.5 ])

In [30]:
#b
col_sums = mat.sum(axis=0)
col_sums

array([37, 13, 30, 40])

In [33]:
#c
max_val = mat.max()
max_pos = np.unravel_index(mat.argmax(), mat.shape)
max_val

np.int64(15)

In [34]:
max_pos

(np.int64(3), np.int64(0))

-----------------------------------------------

10: Reshape the array np.arange(36) into a 3D array of shape (3, 4, 3).

In [36]:
array5 = np.arange(36).reshape(3, 4, 3)
array5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

----------------------------------------------

11: Given arr = np.arange(1, 17).reshape(4, 4). Reverse the order of rows and columns (flip both).

In [37]:
array6 = np.arange(1, 17).reshape(4, 4)
reversed_arr = array6[::-1, ::-1]

In [38]:
array6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
reversed_arr

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

-------------------------------------------------

12: Given ages and names arrays: Get the names of people whose age is between 25 and 40 (inclusive).

In [41]:
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(["Ali", "Sara", "Omar", "Lina", "Khaled", "Nour", "Yara", "Hassan"])

In [42]:
mask = (ages >= 25) & (ages <= 40)
print(names[mask])

['Lina' 'Khaled' 'Hassan']


--------------------------------

13: Using the same ages and names arrays: Replace all ages less than 20 with 20.

In [44]:
ages[ages < 20] = 20
ages

array([23, 45, 20, 34, 28, 51, 20, 39])

---------------------------

14: Create a 6×6 array filled with random integers between 1 and 100 (inclusive). Then set the seed to 123 first.

In [45]:
np.random.seed(123)
rand_arr = np.random.randint(1, 101, size=(6, 6))
rand_arr

array([[ 67,  93,  99,  18,  84,  58],
       [ 87,  98,  97,  48,  74,  33],
       [ 47,  97,  26,  84,  79,  37],
       [ 97,  81,  69,  50,  56,  68],
       [  3,  85,  40,  67,  85,  48],
       [ 62,  49,   8, 100,  93,  53]], dtype=int32)

------------------------------------------

15: Create an array of 10 random numbers from a normal distribution with mean 100 and standard deviation 15.

In [46]:
norm_dist = np.random.normal(100, 15, 10)
norm_dist

array([127.06686834,  85.51674961,  80.25279948,  90.61322265,
        95.09580659,  95.37686206, 112.40676196, 116.06172126,
        54.16633874, 115.08897902])

--------------------------------------

16: From the list colors = ["red", "blue", "green", "yellow", "purple"], randomly select 3 different colors without replacement.

In [47]:
colors = ["red", "blue", "green", "yellow", "purple"]
choice = np.random.choice(colors, 3, replace=False)
choice

array(['blue', 'yellow', 'purple'], dtype='<U6')

----------------------------------------------

17: Shuffle the numbers from 1 to 20 in place.

In [50]:
array7 = np.arange(1, 21)
array7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
np.random.shuffle(array7)
array7

array([ 5,  2, 14, 11,  1,  7, 15,  9, 16,  3, 13,  8, 20,  6, 12, 19,  4,
       18, 17, 10])

Thank You